[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/fpl-proxy/:splat"
  status = 200



[[redirects]]
  from = "/fpl-api/*"
  to = "https://fantasy.premierleague.com/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    Referer = "https://fantasy.premierleague.com/"
